### ISSUE TITLE
viewpls3D/main error "Expecting path to simulation data folder."

### ISSUE THREAD

**Issue by uljad** [christopherbatty/VariationalViscosity3D#3]
I am a little unclear as to how the two mains communicate. How to I define the path? (working on ubuntu). 
How are argv and argc related in this context, why should argc be 2? How do I fix the path to sim folder error?
Thank you

**Comment by christopherbatty** [comment]
The command line argument for the viewpls3d executable should be the path where the output of the simulation is stored.
argv and argc are just standard C/C++ parameters to the main function; they contain the vector of arguments and the number of arguments passed in, respectively. argc must be 2 because the first argument is the executable name and the second argument is the path.

**Comment by uljad** [comment]
I am clear as to the argc and argv theory but my argv[1] is empty and there is a path on arg[0]. When I use that, I get a problem in the fstream of particles_in which there is no reason for.

**Comment by christopherbatty** [comment]
The program expects argc  = 2 and that the path is in argv[1]. If that's not the case, for some reason(?), then you'll probably have to edit the code to get it to work for you.

**Comment by uljad** [comment]
Should I replace the main.cpp file or just run them both and comment out the first main.cpp. Maybe I am running the files erroneously? I am very new to openGL and c++ visualizations. How to deal with the multiple definitions of frame and main()?
![image](https://user-images.githubusercontent.com/53211385/86484171-ea5c2a80-bd55-11ea-8137-93862469f2c4.png)

**Comment by christopherbatty** [comment]
The repository contains two different (independent) programs. The main simulator, and then in the subdirectory viewpls3d, a totally separate program to visualize the results. You should compile them separately.

**Comment by uljad** [comment]
All clear. Thank you and good luck with your awesome research!
