### ISSUE TITLE
Running on visual studio 

### ISSUE THREAD

**Issue by alt0216** [christopherbatty/VariationalViscosity3D#4]
Hi, sorry this is another build issue. I am able to run main.cpp on visual studio but the commond prompt will show a message: "The first parameter should be the folder to write the output liquid meshes into. (eg. c:\output\)" Do you know the reason behind this/how to fix it? Thank you very much.

**Comment by christopherbatty** [comment]
It's just asking you to specify where you want the output to be stored, since the program is not real-time or interactive; instead it dumps out data files that you can then load and view afterward.

**Comment by alt0216** [comment]
Got it, how can I specify the path? Sorry i have just started learning about this.

**Comment by christopherbatty** [comment]
When you run the program from the command line (on Windows for example), it would look something like:
viscosity3d.exe <path>
where <path> is replaced by the path you want it to dump the data to.

**Comment by alt0216** [comment]
Yes I got it to work now. Thank you very much.
